version: '3'
services:
  nginx-unit:
    build: ./unit
    working_dir: /var/www/
    ports:
      - "80:80"
    volumes:
      - ./unit/config.json:/docker-entrypoint.d/config.json
      - ./../.:/var/www

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "fizcult"
      POSTGRES_USER: "fizcult"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "8002:6379"
